# Generated by Django 5.0.7 on 2024-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_registroadminstracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioPrevidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('APOSENTADO', 'Aposentado')], default='ATIVO', max_length=20)),
            ],
        ),
    ]
