# Generated by Django 5.0.7 on 2024-08-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_funcionarioprevidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('salario_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_juros_anual', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('taxa_correcao_mensal', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
            ],
        ),
    ]
