# Generated by Django 5.0.7 on 2024-08-13 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_fgts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('pis_pasep', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualizacaoFGTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.DateField()),
                ('renumeracao_bruta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_fgts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fgts', to='plataforma.empregado')),
            ],
        ),
    ]
