# Generated by Django 5.0.7 on 2024-08-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_empregado_individualizacaofgts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fgts',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionarioprevidencia',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ReceitaFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('atividade', models.CharField(max_length=255)),
                ('num_parcelamento', models.IntegerField()),
                ('objeto', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_vigencia', models.DateField()),
                ('situacao', models.CharField(max_length=255)),
                ('providencia', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.municipio')),
            ],
            options={
                'verbose_name_plural': 'Tabela da Receita Federal',
            },
        ),
    ]
