# Generated by Django 5.0.7 on 2024-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_empregado_nome_alter_fgts_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('circulante', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('circulante', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalancoPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativos', models.ManyToManyField(to='plataforma.ativo')),
                ('passivos', models.ManyToManyField(to='plataforma.passivo')),
            ],
        ),
    ]
